### ISSUE TITLE
聚类答案

### ISSUE THREAD

**Issue by tcxia** [yinzhangyue/AoR#1]
您好，读了一下论文，有一个疑问点，拿您图3的例子来说，若LLM输出的结果是"So the answer is 10%"，不是标准的A,B,C,D，这块是怎么聚合相同答案的呢？

**Comment by yinzhangyue** [comment]
非常感谢您的提问，如果是GSM8K这类开放型问题，我们会采用正则表达式提取答案，这和Self-Consistency选取最一致答案的过程是一致的，然后根据提取到的数字进行聚类。

**Comment by tcxia** [comment]
明白了，期待你们早日开源，可以早点学习学习

**Comment by cyf20** [comment]
你好，作者，代码什么时候开源啊？想学习学习，期待您的回复，谢谢！

**Comment by yinzhangyue** [comment]
已开源，感谢关注~
